#The level of Y axis as you fall into the void where you'll get killed after passing it.
void-height: 15
#Number of logical processors to perform some operations inside the plugin.
threads: 6 #replace by -1 to consume all available threads